version: '2'
networks:
  web:
    driver: "bridge"

services:

  # Reverse proxy: traefik
  reverseproxy:
    image: xamanu/traefik
    command: "--logLevel=ERROR"
    restart: always
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/cert:/cert/"
    labels:
      - "traefik.enable=false" # set to true to expose Monitoring & API
      - "traefik.backend=proxy"
      - "traefik.port=8080"
    networks:
      - "web"

  # XMPP chat server: prosody
  xmpp-server:
    build: "./build/prosody"
    restart: always
    env_file: .env
    volumes:
      - ./data/cert:/cert/:ro
      - ./data/prosody/conf:/etc/prosody/conf.d
      - ./data/prosody/data:/var/lib/prosody/data
    ports:
      - "5222:5222" # 5222/tcp: client to server
      - "5269:5269" # 5269/tcp: server to server
    labels:
      - "traefik.enable=true"
      - "traefik.backend=xmpp-server"
      - "traefik.docker.network=xmpp-server_web"
      - "traefik.port=5280"
      - "traefik.frontend.rule=Host:$XMPP_SERVER_URL,$XMPP_GROUPS_URL;PathPrefix:/_xmpp/"
    networks:
      - web

  # XMPP http upload server: prosody-filer
  xmpp-filer:
    build: "./build/filer"
    restart: always
    env_file: .env
    ports:
      - 5050:5060
    labels:
      - "traefik.enable=true"
      - "traefik.backend=xmpp-filer"
      - "traefik.docker.network=xmpp-server_web"
      - "traefik.frontend.rule=Host:$XMPP_SERVER_URL,$XMPP_GROUPS_URL;PathPrefix:/_xmpp/upload"
    networks:
      - web
